//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKaroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        public tblArea()
        {
            this.tblCustomers = new HashSet<tblCustomer>();
            this.tblVendors = new HashSet<tblVendor>();
        }
    
        public int AreaCode { get; set; }
        public string AreaDescription { get; set; }
        public string AreaCategory { get; set; }
        public string AreaEnteredOn { get; set; }
        public string AreaEnteredBy { get; set; }
        public string AreaUpdatedOn { get; set; }
        public string AreaUpdatedBy { get; set; }
        public int CityID { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
        public virtual ICollection<tblVendor> tblVendors { get; set; }
    }
}
