//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKaroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookingItem
    {
        public tblBookingItem()
        {
            this.tblCustomers = new HashSet<tblCustomer>();
        }
    
        public int BookingID { get; set; }
        public string BookingDescription { get; set; }
        public string BookingDate { get; set; }
        public string BookingTime { get; set; }
        public string BookingType { get; set; }
        public string BookingStatus { get; set; }
        public int VendorID { get; set; }
    
        public virtual tblVendor tblVendor { get; set; }
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
    }
}
