//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKaroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblBookingItems = new HashSet<tblBookingItem>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerCategory { get; set; }
        public string CustomerLandLine { get; set; }
        public string CustomerCountry { get; set; }
        public string CustomerMobilePrimary { get; set; }
        public string CustomerMobileSecondary { get; set; }
        public string CustomerCNIC { get; set; }
        public int AreaCode { get; set; }
        public string CustomerEnteredOn { get; set; }
        public string CustomerEnteredBy { get; set; }
        public string CustomerUpdatedOn { get; set; }
        public string CustomerUpdatedBy { get; set; }
        public string CustomerUserPassword { get; set; }
        public string CustomerUserType { get; set; }
        public string CustomerUserStatus { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tblArea tblArea { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblBookingItem> tblBookingItems { get; set; }
    }
}
