//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKaroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacility
    {
        public tblFacility()
        {
            this.tblVendors = new HashSet<tblVendor>();
        }
    
        public int FacilityID { get; set; }
        public string FacilityName { get; set; }
        public string FacilityDescription { get; set; }
        public string FacilityRemarks { get; set; }
    
        public virtual ICollection<tblVendor> tblVendors { get; set; }
    }
}
