//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKaroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public tblRole()
        {
            this.tblUsers = new HashSet<tblUser>();
            this.tblUsers1 = new HashSet<tblUser>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public string RoleRemarks { get; set; }
    
        public virtual ICollection<tblUser> tblUsers { get; set; }
        public virtual ICollection<tblUser> tblUsers1 { get; set; }
    }
}
