//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKaroMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblCustomers = new HashSet<tblCustomer>();
            this.tblVendors = new HashSet<tblVendor>();
            this.tblRoles = new HashSet<tblRole>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserDisplayName { get; set; }
        public string UsePassword { get; set; }
        public Nullable<System.DateTime> UseLast_Login { get; set; }
        public Nullable<System.DateTime> UserRegistration { get; set; }
        public string UserType { get; set; }
        public string UserPreviousPasswordDate { get; set; }
        public Nullable<System.DateTime> UserLoginDate { get; set; }
        public string UserAddress { get; set; }
        public int RoleID { get; set; }
    
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
        public virtual tblRole tblRole { get; set; }
        public virtual ICollection<tblVendor> tblVendors { get; set; }
        public virtual ICollection<tblRole> tblRoles { get; set; }
    }
}
